options:
  trainer_options:
    video_log_frequency: -1
    log_frequency: 2
    max_video_length: 1000
    eval_interaction_steps: 4000
    eval_episode_length: 1000
    training_logger_params:
      fps: 60
  train_iterations: 125
  agent: mbrl_agent
  environment: MbrlSafexp-PointSimpleGoal1-v0

agents:
  mbrl_agent: 
    policy: random_shooting_mpc
    constraint: constraint_model