models:
  mlp_ensemble:
    ensemble_size: 15
    batch_size: 64
    validation_split: 0.2
    learning_rate: 0.00025
    learning_rate_schedule: True
    training_steps: 5000
    mlp_params:
      n_layers: 4
      units: 128
      activation: tf.nn.relu
      dropout_rate: 0.0

  constraint_model:
    batch_size: 64
    validation_split: 0.2
    learning_rate: 0.0025
    learning_rate_schedule: True
    training_steps: 2000
    c_level: 2.0
    mlp_params:
      n_layers: 2
      units: 128
      activation: tf.nn.relu
      dropout_rate: 0.0
